name: DLT NYC Taxi Loader (deploy)
concurrency: 1
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: "Setup Config and deploy bundle"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - run: |
            echo "BUNDLE_NAME=$(databricks bundle validate | jq -r '.bundle.name')" >> $GITHUB_OUTPUT
      - run: databricks workspace import-dir --overwrite init-scripts /Shared/${{ steps.version.outputs.BUNDLE_NAME }}/init-scripts/
      - run: databricks bundle deploy
        working-directory: ./my_project
        env:
          DATABRICKS_TOKEN: ${{ secrets.E2_SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev
  pipeline_update:
    name: "Run pipeline update"
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - run: databricks bundle run my_project_job --refresh-all
        working-directory: ./my_project
        env:
          DATABRICKS_TOKEN: ${{ secrets.E2_SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev